services:
  frontend:
    build: ./frontend
    user: "node"
    working_dir: /home/node/app
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/home/node/app
    command: "npm run dev -- --host"
  backend:
    build: ./backend
    working_dir: /opt/app
    env_file: "backend.env"
    ports:
      - 8080:8080
    volumes:
      - ./backend:/opt/app
    command: "./gradlew bootRun"
  proxy:
    build: ./proxy
    ports:
      - 80:80
